### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Xephobia** [WoefulWolf/Blender-Rich-Presence#2]
I have waited an certain amount of time (more than 15 seconds) it do not show in discord. I have enlabled the addon
version of blender : 2.82a
version of discord : Stable 56922 (a6ccbca) on windows 10

**Comment by WoefulWolf** [comment]
Sorry for the late reply;
Do you have Game Activity enabled in Discord?
Does Discord recognize that Blender is running? (even if not through the mod, just standard)
No errors in the Blender Console Window after startup?

**Comment by Xephobia** [comment]
Discord can reconise blender as "Blender preferences" nothing interesting on blender console `Read prefs: C:\Users\F.A.(X)\AppData\Roaming\Blender Foundation\Blender\2.82\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender 2.82\2.82\python
mb_lab updater verbose is enabled
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_install_popup'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_install_popup'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_check_now'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_check_now'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_update_now'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_update_now'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_update_target'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_update_target'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_install_manually'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_install_manually'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_updated_successful'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_updated_successful'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_restore_backup'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_restore_backup'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_ignore'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_ignore'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_end_background'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_end_background'>
mb_lab Updater: Read in json settings from file
module changed on disk: 'C:\\Program Files\\Blender Foundation\\Blender 2.82\\2.82\\scripts\\addons\\object_print3d_utils\\__init__.py' reloading...
Registered Carver
Registered Power Sequencer with 75 modules
Registered Animation Nodes
Armory: Proxy objects synchronized
Warning: property 'release_confirm' not found in keymap item 'OperatorProperties'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\F.A.(X)\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\bsp_tool.py'`

**Comment by WoefulWolf** [comment]
The warnings don't seem to be related. You say you used the _Install from Zip_ option?
It is probably recognizing it as "Blender preferences" because you still have the add-on menu open.
Only other thing I can think of right now is possibly your Blender install is being weird? Or another add-on is messing with the internal Python.

I just made a fresh install of Blender v2.82a, downloaded the repo as ZIP, installed the ZIP, enabled and it worked fine. Please let me know if there are any other issues or if you manage to find anything.
