### ISSUE TITLE
Error rendering in terminal

### ISSUE THREAD

**Issue by D1360-64RC14** [WoefulWolf/Blender-Rich-Presence#3]
The plugin gets a simple error when rendering the blend file on terminal (in this case, Windows CMD)

![Terminal](https://user-images.githubusercontent.com/33406930/80925829-68598080-8d69-11ea-8d9d-2811fca3d29d.png)

(Sorry my english)

**Comment by D1360-64RC14** [comment]
In my tests, i observed that the function `update()` doesn't run when rendering on terminal. Thus, occurring the `NameError: name 'project_path' is not defined`.
I fixed this calling `update()` into the `render_started()` function.

**Comment by WoefulWolf** [comment]
Resolved in latest version.
