### ISSUE TITLE
Face and Vertex Count Innacurate

### ISSUE THREAD

**Issue by LoadingL0n3ly** [WoefulWolf/Blender-Rich-Presence#4]
The title kind of explains the issue, when using the add-on, the discord sent to discord varies severly from the data shown in blender.
![image](https://user-images.githubusercontent.com/75146193/117576867-49887b00-b09c-11eb-8231-7c6a6f11a114.png)

![image](https://user-images.githubusercontent.com/75146193/117576901-64f38600-b09c-11eb-822e-447fed774d79.png)

**Comment by WoefulWolf** [comment]
This was due to modifiers not being taken into account.
Resolved in latest version.
